@baseUrl = http://<HOST>:<PORT>/api/characters

###
GET {{baseUrl}}
Authorization: Bearer <token>

###
GET {{baseUrl}}?query=value
Authorization: Bearer <token>

###
GET {{baseUrl}}/:id
Authorization: Bearer <token>

###
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer <token>

{
  "name": "Test Test",
  "image": "test/test",
  "age": 25,
  "weight": 90,
  "history": "test history",
}

###
PUT {{baseUrl}}/:id
Content-Type: application/json
Authorization: Bearer <token>

{
  "name": "Test Test update",
  "image": "test/test",
  "age": 25,
  "weight": 90.3,
  "history": "test history"
}

###
DELETE {{baseUrl}}/:id
Authorization: Bearer <token>